# This file tells repo-file-sync-action which files to sync
# from this .github repo to other repos in the org

group:
  repos: |
    openalea/astk
    openalea/caribu
    openalea/plantgl
    openalea/hydroroot
    openalea/PyRATP
    openalea/mtg
    openalea/hydroshoot
    openalea/StructureAnalysis
    openalea/oalab
    openalea/oawidgets
    openalea/core
    openalea/grapheditor
    openalea/RSML
    openalea/weberpenn
    openalea/visualea
    openalea/scipack
    openalea/PyQGLViewer
    openalea/metafspm
    openalea/agroservices
    openalea/Root-CyNAPS
    openalea/rhizodep
    openalea/adel
    openalea/lpy
    openalea/phenomenal
  files:
    - source: workflow-templates/
      dest: .github/workflows/
      exclude: |
        openalea_ci.properties.json
        openalea_web.svg
      deleteOrphaned: true