# This file tells repo-file-sync-action which files to sync
# from this .github repo to other repos in the org

group:
  repos: |
    openalea.astk
  files:
    - source: workflow-templates/
      dest: .github/workflows/
      exclude: |
        openalea_ci.properties.json
        openalea_web.svg
      deleteOrphaned: true