name: OpenAlea CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder step
        run: echo "This is a placeholder workflow for openalea ci"
    # To enable the actual ci, remove lines after 'build:' and uncomment below:
    # uses: openalea/action-build-publish-anaconda/.github/workflows/openalea_ci.yml@main
    # secrets:
    #   anaconda_token: ${{ secrets.ANACONDA_TOKEN }}