name: Sync Workflow Templates

on:
  workflow_dispatch: # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run repo-file-sync-action
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.ORG_BOT_TOKEN }}
          COMMIT_PREFIX: '[no ci]'
          PR_BODY: 'openalea-bot: Update your ci workflow settings'